window.CRISIS_DATA=[
{id:"GCM-001",name:"Sudan Conflict",country:"Sudan",region:"East Africa",lat:15.5007,lng:32.5599,category:"Conflict",severity:5,status:"Active",trend:"Worsening",start:"2023-04-15",description:"Ongoing armed conflict with severe humanitarian consequences and widespread displacement.",source:"Sample record"},
{id:"GCM-002",name:"Red Sea Shipping Disruption",country:"Yemen / Red Sea",region:"Middle East",lat:14.8,lng:42.9,category:"Infrastructure & Trade",severity:4,status:"Active",trend:"Worsening",start:"2026-09-10",description:"Elevated disruption risk affecting maritime traffic through the Red Sea and Bab el-Mandeb chokepoint.",source:"Sample record"},
{id:"GCM-003",name:"Ukraine War",country:"Ukraine",region:"Eastern Europe",lat:49,lng:32,category:"Conflict",severity:5,status:"Active",trend:"Stable",start:"2022-02-24",description:"Large-scale interstate war with continued military, humanitarian, and infrastructure impacts.",source:"Sample record"},
{id:"GCM-004",name:"Haiti Security Crisis",country:"Haiti",region:"Caribbean",lat:18.5944,lng:-72.3074,category:"Political & Security",severity:4,status:"Active",trend:"Worsening",start:"2024-01-01",description:"Persistent political instability and armed-group violence affecting governance and public security.",source:"Sample record"},
{id:"GCM-005",name:"Taiwan Strait Tensions",country:"Taiwan",region:"East Asia",lat:23.6978,lng:120.9605,category:"Geopolitical",severity:4,status:"Watch",trend:"Stable",start:"2026-01-01",description:"Heightened strategic and military tension across the Taiwan Strait with regional security implications.",source:"Sample record"},
{id:"GCM-006",name:"Sahel Insurgency",country:"Mali / Burkina Faso / Niger",region:"West Africa",lat:14.5,lng:-1.5,category:"Security",severity:4,status:"Active",trend:"Worsening",start:"2020-01-01",description:"Persistent militant violence, weak state control, and displacement across the central Sahel.",source:"Sample record"},
{id:"GCM-007",name:"Horn of Africa Drought",country:"Somalia / Ethiopia / Kenya",region:"East Africa",lat:5.15,lng:45.2,category:"Humanitarian",severity:3,status:"Active",trend:"Improving",start:"2025-11-01",description:"Food insecurity and water stress remain elevated after repeated drought cycles.",source:"Sample record"},
{id:"GCM-008",name:"Panama Canal Water Stress",country:"Panama",region:"Central America",lat:9.08,lng:-79.68,category:"Infrastructure & Trade",severity:3,status:"Watch",trend:"Stable",start:"2026-05-01",description:"Water availability constraints may affect canal throughput and shipping reliability.",source:"Sample record"},
{id:"GCM-009",name:"Caucasus Border Tensions",country:"Armenia / Azerbaijan",region:"Caucasus",lat:40.1,lng:45,category:"Geopolitical",severity:2,status:"Watch",trend:"Stable",start:"2026-06-01",description:"Residual border and diplomatic tension with potential for localized escalation.",source:"Sample record"},
{id:"GCM-010",name:"Western Pacific Typhoon Emergency",country:"Philippines",region:"Southeast Asia",lat:14.5995,lng:120.9842,category:"Natural Disaster",severity:4,status:"Active",trend:"Improving",start:"2026-09-15",description:"Major storm impacts include flooding, infrastructure damage, and emergency response operations.",source:"Sample record"},
{id:"GCM-011",name:"Andean Political Unrest",country:"Peru",region:"South America",lat:-12.0464,lng:-77.0428,category:"Political & Security",severity:2,status:"Watch",trend:"Stable",start:"2026-07-12",description:"Localized protest activity and political instability are under continued observation.",source:"Sample record"},
{id:"GCM-012",name:"Eastern Mediterranean Energy Dispute",country:"Eastern Mediterranean",region:"Mediterranean",lat:34.4,lng:32,category:"Energy",severity:3,status:"Watch",trend:"Worsening",start:"2026-08-05",description:"Competing maritime and energy claims are elevating geopolitical tension around offshore resources.",source:"Sample record"}
];