window.STOCK_DATA=[
{id:"STK-001",ticker:"NVDA",company:"NVIDIA",sector:"Technology",risk:7,upside:32,conviction:8,status:"Watch",horizon:"Medium-term",price:0,target:0,thesis:"AI compute leadership, data-center demand, and ecosystem strength make it a high-interest growth name.",catalyst:"Earnings, new architecture cycles, hyperscaler capex."},
{id:"STK-002",ticker:"PLTR",company:"Palantir",sector:"Technology",risk:8,upside:40,conviction:7,status:"Researching",horizon:"Long-term",price:0,target:0,thesis:"Potential operating leverage and expanding commercial adoption make it an interesting software platform to monitor.",catalyst:"Commercial growth and contract wins."},
{id:"STK-003",ticker:"RTX",company:"RTX",sector:"Industrials",risk:4,upside:18,conviction:7,status:"Watch",horizon:"Long-term",price:0,target:0,thesis:"Defense exposure, aerospace aftermarket demand, and long-duration government programs support a steadier thesis.",catalyst:"Defense budgets, backlog conversion, aerospace demand."},
{id:"STK-004",ticker:"LMT",company:"Lockheed Martin",sector:"Industrials",risk:3,upside:14,conviction:6,status:"Watch",horizon:"Long-term",price:0,target:0,thesis:"Large defense backlog and strategic programs make this a lower-volatility defense exposure.",catalyst:"Program awards and defense spending."},
{id:"STK-005",ticker:"TSLA",company:"Tesla",sector:"Consumer Discretionary",risk:9,upside:45,conviction:5,status:"Researching",horizon:"Long-term",price:0,target:0,thesis:"High uncertainty but potentially large optionality tied to autonomy, energy, manufacturing, and robotics.",catalyst:"Autonomy milestones, margins, energy growth."},
{id:"STK-006",ticker:"GOOGL",company:"Alphabet",sector:"Communication Services",risk:4,upside:22,conviction:8,status:"Watch",horizon:"Long-term",price:0,target:0,thesis:"Strong cash generation, cloud growth, and AI distribution create a balanced risk/reward profile.",catalyst:"AI monetization, cloud margins, advertising trends."},
{id:"STK-007",ticker:"AMZN",company:"Amazon",sector:"Consumer Discretionary",risk:5,upside:25,conviction:8,status:"Watch",horizon:"Long-term",price:0,target:0,thesis:"AWS, advertising, and retail efficiency provide multiple growth and margin drivers.",catalyst:"AWS acceleration and margin expansion."},
{id:"STK-008",ticker:"RKLB",company:"Rocket Lab",sector:"Industrials",risk:10,upside:70,conviction:4,status:"Researching",horizon:"Long-term",price:0,target:0,thesis:"Highly speculative aerospace exposure with meaningful upside if launch and space-systems execution compounds.",catalyst:"Neutron milestones and launch cadence."}
];